
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file CheckOut.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using cunghoc3_AssetManager.Entities.Validation;
#endregion

namespace cunghoc3_AssetManager.Entities
{
	///<summary>
	/// An object representation of the 'CheckOut' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class CheckOutBase : EntityBase, ICheckOut, IEntityId<CheckOutKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private CheckOutEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private CheckOutEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private CheckOutEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<CheckOut> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CheckOutEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CheckOutEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CheckOutBase"/> instance.
		///</summary>
		public CheckOutBase()
		{
			this.entityData = new CheckOutEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CheckOutBase"/> instance.
		///</summary>
		///<param name="_assetId"></param>
		///<param name="_checkOutDate"></param>
		///<param name="_comment"></param>
		///<param name="_user"></param>
		///<param name="_computer"></param>
		///<param name="_status"></param>
		public CheckOutBase(System.String _assetId, System.DateTime? _checkOutDate, System.String _comment, 
			System.String _user, System.String _computer, System.Int16? _status)
		{
			this.entityData = new CheckOutEntityData();
			this.backupData = null;

			this.AssetId = _assetId;
			this.CheckOutDate = _checkOutDate;
			this.Comment = _comment;
			this.User = _user;
			this.Computer = _computer;
			this.Status = _status;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="CheckOut"/> instance.
		///</summary>
		///<param name="_assetId"></param>
		///<param name="_checkOutDate"></param>
		///<param name="_comment"></param>
		///<param name="_user"></param>
		///<param name="_computer"></param>
		///<param name="_status"></param>
		public static CheckOut CreateCheckOut(System.String _assetId, System.DateTime? _checkOutDate, System.String _comment, 
			System.String _user, System.String _computer, System.Int16? _status)
		{
			CheckOut newCheckOut = new CheckOut();
			newCheckOut.AssetId = _assetId;
			newCheckOut.CheckOutDate = _checkOutDate;
			newCheckOut.Comment = _comment;
			newCheckOut.User = _user;
			newCheckOut.Computer = _computer;
			newCheckOut.Status = _status;
			return newCheckOut;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(CheckOutColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CheckOutColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AssetId property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String AssetId
		{
			get
			{
				return this.entityData.AssetId; 
			}
			
			set
			{
				if (this.entityData.AssetId == value)
					return;
				
                OnPropertyChanging("AssetId");                    
				OnColumnChanging(CheckOutColumn.AssetId, this.entityData.AssetId);
				this.entityData.AssetId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CheckOutColumn.AssetId, this.entityData.AssetId);
				OnPropertyChanged("AssetId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CheckOutDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsCheckOutDateNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? CheckOutDate
		{
			get
			{
				return this.entityData.CheckOutDate; 
			}
			
			set
			{
				if (this.entityData.CheckOutDate == value)
					return;
				
                OnPropertyChanging("CheckOutDate");                    
				OnColumnChanging(CheckOutColumn.CheckOutDate, this.entityData.CheckOutDate);
				this.entityData.CheckOutDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CheckOutColumn.CheckOutDate, this.entityData.CheckOutDate);
				OnPropertyChanged("CheckOutDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Comment property. 
		///		
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String Comment
		{
			get
			{
				return this.entityData.Comment; 
			}
			
			set
			{
				if (this.entityData.Comment == value)
					return;
				
                OnPropertyChanging("Comment");                    
				OnColumnChanging(CheckOutColumn.Comment, this.entityData.Comment);
				this.entityData.Comment = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CheckOutColumn.Comment, this.entityData.Comment);
				OnPropertyChanged("Comment");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the User property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String User
		{
			get
			{
				return this.entityData.User; 
			}
			
			set
			{
				if (this.entityData.User == value)
					return;
				
                OnPropertyChanging("User");                    
				OnColumnChanging(CheckOutColumn.User, this.entityData.User);
				this.entityData.User = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CheckOutColumn.User, this.entityData.User);
				OnPropertyChanged("User");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Computer property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Computer
		{
			get
			{
				return this.entityData.Computer; 
			}
			
			set
			{
				if (this.entityData.Computer == value)
					return;
				
                OnPropertyChanging("Computer");                    
				OnColumnChanging(CheckOutColumn.Computer, this.entityData.Computer);
				this.entityData.Computer = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CheckOutColumn.Computer, this.entityData.Computer);
				OnPropertyChanged("Computer");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Status property. 
		///		
		/// </summary>
		/// <value>This type is smallint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (short)0. It is up to the developer
		/// to check the value of IsStatusNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int16? Status
		{
			get
			{
				return this.entityData.Status; 
			}
			
			set
			{
				if (this.entityData.Status == value)
					return;
				
                OnPropertyChanging("Status");                    
				OnColumnChanging(CheckOutColumn.Status, this.entityData.Status);
				this.entityData.Status = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CheckOutColumn.Status, this.entityData.Status);
				OnPropertyChanged("Status");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("AssetId", "Asset Id", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("User", "User", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Computer", "Computer", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "CheckOut"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "AssetId", "CheckOutDate", "Comment", "User", "Computer", "Status"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CheckOutEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (CheckOut) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<CheckOut>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as CheckOut);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed CheckOut Entity 
		///</summary>
		protected virtual CheckOut Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			CheckOut copy = new CheckOut();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
				copy.AssetId = this.AssetId;
				copy.CheckOutDate = this.CheckOutDate;
				copy.Comment = this.Comment;
				copy.User = this.User;
				copy.Computer = this.Computer;
				copy.Status = this.Status;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed CheckOut Entity 
		///</summary>
		public virtual CheckOut Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed CheckOut Entity which is a deep copy of the current entity.
		///</summary>
		public virtual CheckOut DeepCopy()
		{
			return EntityHelper.Clone<CheckOut>(this as CheckOut);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as CheckOutEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new CheckOutEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as CheckOutEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(CheckOutColumn column)
		{
			switch(column)
			{
					case CheckOutColumn.Id:
					return entityData.Id != _originalData.Id;
					case CheckOutColumn.AssetId:
					return entityData.AssetId != _originalData.AssetId;
					case CheckOutColumn.CheckOutDate:
					return entityData.CheckOutDate != _originalData.CheckOutDate;
					case CheckOutColumn.Comment:
					return entityData.Comment != _originalData.Comment;
					case CheckOutColumn.User:
					return entityData.User != _originalData.User;
					case CheckOutColumn.Computer:
					return entityData.Computer != _originalData.Computer;
					case CheckOutColumn.Status:
					return entityData.Status != _originalData.Status;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< CheckOutColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.AssetId != _originalData.AssetId;
			result = result || entityData.CheckOutDate != _originalData.CheckOutDate;
			result = result || entityData.Comment != _originalData.Comment;
			result = result || entityData.User != _originalData.User;
			result = result || entityData.Computer != _originalData.Computer;
			result = result || entityData.Status != _originalData.Status;
			return result;
		}	
		
		///<summary>
		///  Returns a CheckOut Entity with the original data.
		///</summary>
		public CheckOut GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateCheckOut(
				_originalData.AssetId,
				_originalData.CheckOutDate,
				_originalData.Comment,
				_originalData.User,
				_originalData.Computer,
				_originalData.Status
				);
				
			return (CheckOut)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="CheckOutBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is CheckOutBase)
				return ValueEquals(this, (CheckOutBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="CheckOutBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.AssetId == null) ? string.Empty : this.AssetId.ToString()).GetHashCode() ^ 
					((this.CheckOutDate == null) ? string.Empty : this.CheckOutDate.ToString()).GetHashCode() ^ 
					((this.Comment == null) ? string.Empty : this.Comment.ToString()).GetHashCode() ^ 
					((this.User == null) ? string.Empty : this.User.ToString()).GetHashCode() ^ 
					((this.Computer == null) ? string.Empty : this.Computer.ToString()).GetHashCode() ^ 
					((this.Status == null) ? string.Empty : this.Status.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CheckOutBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CheckOutBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="CheckOutBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="CheckOutBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CheckOutBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(CheckOutBase Object1, CheckOutBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.AssetId != null && Object2.AssetId != null )
			{
				if (Object1.AssetId != Object2.AssetId)
					equal = false;
			}
			else if (Object1.AssetId == null ^ Object2.AssetId == null )
			{
				equal = false;
			}
			if ( Object1.CheckOutDate != null && Object2.CheckOutDate != null )
			{
				if (Object1.CheckOutDate != Object2.CheckOutDate)
					equal = false;
			}
			else if (Object1.CheckOutDate == null ^ Object2.CheckOutDate == null )
			{
				equal = false;
			}
			if ( Object1.Comment != null && Object2.Comment != null )
			{
				if (Object1.Comment != Object2.Comment)
					equal = false;
			}
			else if (Object1.Comment == null ^ Object2.Comment == null )
			{
				equal = false;
			}
			if ( Object1.User != null && Object2.User != null )
			{
				if (Object1.User != Object2.User)
					equal = false;
			}
			else if (Object1.User == null ^ Object2.User == null )
			{
				equal = false;
			}
			if ( Object1.Computer != null && Object2.Computer != null )
			{
				if (Object1.Computer != Object2.Computer)
					equal = false;
			}
			else if (Object1.Computer == null ^ Object2.Computer == null )
			{
				equal = false;
			}
			if ( Object1.Status != null && Object2.Status != null )
			{
				if (Object1.Status != Object2.Status)
					equal = false;
			}
			else if (Object1.Status == null ^ Object2.Status == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((CheckOutBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static CheckOutComparer GetComparer()
        {
            return new CheckOutComparer();
        }
        */

        // Comparer delegates back to CheckOut
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(CheckOut rhs, CheckOutColumn which)
        {
            switch (which)
            {
            	
            	
            	case CheckOutColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case CheckOutColumn.AssetId:
            		return this.AssetId.CompareTo(rhs.AssetId);
            		
            		                 
            	
            	
            	case CheckOutColumn.CheckOutDate:
            		return this.CheckOutDate.Value.CompareTo(rhs.CheckOutDate.Value);
            		
            		                 
            	
            	
            	case CheckOutColumn.Comment:
            		return this.Comment.CompareTo(rhs.Comment);
            		
            		                 
            	
            	
            	case CheckOutColumn.User:
            		return this.User.CompareTo(rhs.User);
            		
            		                 
            	
            	
            	case CheckOutColumn.Computer:
            		return this.Computer.CompareTo(rhs.Computer);
            		
            		                 
            	
            	
            	case CheckOutColumn.Status:
            		return this.Status.Value.CompareTo(rhs.Status.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CheckOutKey> Members
		
		// member variable for the EntityId property
		private CheckOutKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual CheckOutKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CheckOutKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("CheckOut")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{8}{7}- Id: {0}{7}- AssetId: {1}{7}- CheckOutDate: {2}{7}- Comment: {3}{7}- User: {4}{7}- Computer: {5}{7}- Status: {6}{7}{9}", 
				this.Id,
				(this.AssetId == null) ? string.Empty : this.AssetId.ToString(),
				(this.CheckOutDate == null) ? string.Empty : this.CheckOutDate.ToString(),
				(this.Comment == null) ? string.Empty : this.Comment.ToString(),
				(this.User == null) ? string.Empty : this.User.ToString(),
				(this.Computer == null) ? string.Empty : this.Computer.ToString(),
				(this.Status == null) ? string.Empty : this.Status.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'CheckOut' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class CheckOutEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CheckOut"</remarks>
		public System.Int64 Id;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// AssetId : 
		/// </summary>
		public System.String AssetId = null;
		
		/// <summary>
		/// CheckOutDate : 
		/// </summary>
		public System.DateTime? CheckOutDate = null;
		
		/// <summary>
		/// Comment : 
		/// </summary>
		public System.String Comment = null;
		
		/// <summary>
		/// User : 
		/// </summary>
		public System.String User = null;
		
		/// <summary>
		/// Computer : 
		/// </summary>
		public System.String Computer = null;
		
		/// <summary>
		/// Status : 
		/// </summary>
		public System.Int16? Status = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			CheckOutEntityData _tmp = new CheckOutEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.AssetId = this.AssetId;
			_tmp.CheckOutDate = this.CheckOutDate;
			_tmp.Comment = this.Comment;
			_tmp.User = this.User;
			_tmp.Computer = this.Computer;
			_tmp.Status = this.Status;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			CheckOutEntityData _tmp = new CheckOutEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.AssetId = this.AssetId;
			_tmp.CheckOutDate = this.CheckOutDate;
			_tmp.Comment = this.Comment;
			_tmp.User = this.User;
			_tmp.Computer = this.Computer;
			_tmp.Status = this.Status;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CheckOutColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(CheckOutColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CheckOutColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(CheckOutColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CheckOutColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(CheckOutColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				CheckOutEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CheckOutEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CheckOutColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(CheckOutColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CheckOutEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CheckOutEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region CheckOutEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="CheckOut"/> object.
	/// </remarks>
	public class CheckOutEventArgs : System.EventArgs
	{
		private CheckOutColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the CheckOutEventArgs class.
		///</summary>
		public CheckOutEventArgs(CheckOutColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CheckOutEventArgs class.
		///</summary>
		public CheckOutEventArgs(CheckOutColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The CheckOutColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CheckOutColumn" />
		public CheckOutColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all CheckOut related events.
	///</summary>
	public delegate void CheckOutEventHandler(object sender, CheckOutEventArgs e);
	
	#region CheckOutComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CheckOutComparer : System.Collections.Generic.IComparer<CheckOut>
	{
		CheckOutColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CheckOutComparer"/> class.
        /// </summary>
		public CheckOutComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:CheckOutComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CheckOutComparer(CheckOutColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="CheckOut"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="CheckOut"/> to compare.</param>
        /// <param name="b">The second <c>CheckOut</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(CheckOut a, CheckOut b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(CheckOut entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(CheckOut a, CheckOut b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CheckOutColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CheckOutKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="CheckOut"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CheckOutKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CheckOutKey class.
		/// </summary>
		public CheckOutKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CheckOutKey class.
		/// </summary>
		public CheckOutKey(CheckOutBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CheckOutKey class.
		/// </summary>
		public CheckOutKey(System.Int64 _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CheckOutBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CheckOutBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Int64 _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.Int64 Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["Id"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CheckOutColumn Enum
	
	/// <summary>
	/// Enumerate the CheckOut columns.
	/// </summary>
	[Serializable]
	public enum CheckOutColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		Id = 1,
		/// <summary>
		/// AssetId : 
		/// </summary>
		[EnumTextValue("AssetId")]
		[ColumnEnum("AssetId", typeof(System.String), System.Data.DbType.String, false, false, true, 10)]
		AssetId = 2,
		/// <summary>
		/// CheckOutDate : 
		/// </summary>
		[EnumTextValue("CheckOutDate")]
		[ColumnEnum("CheckOutDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		CheckOutDate = 3,
		/// <summary>
		/// Comment : 
		/// </summary>
		[EnumTextValue("Comment")]
		[ColumnEnum("Comment", typeof(System.String), System.Data.DbType.String, false, false, true)]
		Comment = 4,
		/// <summary>
		/// User : 
		/// </summary>
		[EnumTextValue("User")]
		[ColumnEnum("User", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		User = 5,
		/// <summary>
		/// Computer : 
		/// </summary>
		[EnumTextValue("Computer")]
		[ColumnEnum("Computer", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Computer = 6,
		/// <summary>
		/// Status : 
		/// </summary>
		[EnumTextValue("Status")]
		[ColumnEnum("Status", typeof(System.Int16), System.Data.DbType.Int16, false, false, true)]
		Status = 7
	}//End enum

	#endregion CheckOutColumn Enum

} // end namespace
