using System;
using System.ComponentModel;

namespace cunghoc3_AssetManager.Entities
{
	/// <summary>
	///		The data structure representation of the 'AssetLiquidation' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAssetLiquidation 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "AssetLiquidation"</remarks>
		System.String Id { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalId { get; set; }
			
		
		
		/// <summary>
		/// AssetId : 
		/// </summary>
		System.String  AssetId  { get; set; }
		
		/// <summary>
		/// Amount : 
		/// </summary>
		System.Int32  Amount  { get; set; }
		
		/// <summary>
		/// DepartmentUsedId : 
		/// </summary>
		System.String  DepartmentUsedId  { get; set; }
		
		/// <summary>
		/// LiDateTime : 
		/// </summary>
		System.DateTime  LiDateTime  { get; set; }
		
		/// <summary>
		/// LiPrice : 
		/// </summary>
		System.Int64  LiPrice  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


