using System;
using System.ComponentModel;

namespace cunghoc3_AssetManager.Entities
{
	/// <summary>
	///		The data structure representation of the 'CheckOut' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ICheckOut 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CheckOut"</remarks>
		System.Int64 Id { get; set; }
				
		
		
		/// <summary>
		/// AssetId : 
		/// </summary>
		System.String  AssetId  { get; set; }
		
		/// <summary>
		/// CheckOutDate : 
		/// </summary>
		System.DateTime?  CheckOutDate  { get; set; }
		
		/// <summary>
		/// Comment : 
		/// </summary>
		System.String  Comment  { get; set; }
		
		/// <summary>
		/// User : 
		/// </summary>
		System.String  User  { get; set; }
		
		/// <summary>
		/// Computer : 
		/// </summary>
		System.String  Computer  { get; set; }
		
		/// <summary>
		/// Status : 
		/// </summary>
		System.Int16?  Status  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


