using System;
using System.ComponentModel;

namespace cunghoc3_AssetManager.Entities
{
	/// <summary>
	///		The data structure representation of the 'Image' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IImage 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Image"</remarks>
		System.Int64 Id { get; set; }
				
		
		
		/// <summary>
		/// AssetId : 
		/// </summary>
		System.String  AssetId  { get; set; }
		
		/// <summary>
		/// ImageURL : 
		/// </summary>
		System.String  ImageUrl  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


