using System;
using System.ComponentModel;

namespace cunghoc3_AssetManager.Entities
{
	/// <summary>
	///		The data structure representation of the 'WarrantyAsset' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IWarrantyAsset 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "WarrantyAsset"</remarks>
		System.String Id { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalId { get; set; }
			
		
		
		/// <summary>
		/// AsssetId : 
		/// </summary>
		System.String  AsssetId  { get; set; }
		
		/// <summary>
		/// DepartmentUsedId : 
		/// </summary>
		System.String  DepartmentUsedId  { get; set; }
		
		/// <summary>
		/// PartnerId : 
		/// </summary>
		System.String  PartnerId  { get; set; }
		
		/// <summary>
		/// WarDateTime : 
		/// </summary>
		System.DateTime  WarDateTime  { get; set; }
		
		/// <summary>
		/// DeadlineWar : 
		/// </summary>
		System.DateTime?  DeadlineWar  { get; set; }
		
		/// <summary>
		/// Address : 
		/// </summary>
		System.String  Address  { get; set; }
		
		/// <summary>
		/// PersonWar : 
		/// </summary>
		System.String  PersonWar  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


