
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file WarrantyAsset.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using cunghoc3_AssetManager.Entities.Validation;
#endregion

namespace cunghoc3_AssetManager.Entities
{
	///<summary>
	/// An object representation of the 'WarrantyAsset' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class WarrantyAssetBase : EntityBase, IWarrantyAsset, IEntityId<WarrantyAssetKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private WarrantyAssetEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private WarrantyAssetEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private WarrantyAssetEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<WarrantyAsset> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event WarrantyAssetEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event WarrantyAssetEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="WarrantyAssetBase"/> instance.
		///</summary>
		public WarrantyAssetBase()
		{
			this.entityData = new WarrantyAssetEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="WarrantyAssetBase"/> instance.
		///</summary>
		///<param name="_id"></param>
		///<param name="_asssetId"></param>
		///<param name="_departmentUsedId"></param>
		///<param name="_partnerId"></param>
		///<param name="_warDateTime"></param>
		///<param name="_deadlineWar"></param>
		///<param name="_address"></param>
		///<param name="_personWar"></param>
		public WarrantyAssetBase(System.String _id, System.String _asssetId, System.String _departmentUsedId, 
			System.String _partnerId, System.DateTime _warDateTime, System.DateTime? _deadlineWar, 
			System.String _address, System.String _personWar)
		{
			this.entityData = new WarrantyAssetEntityData();
			this.backupData = null;

			this.Id = _id;
			this.AsssetId = _asssetId;
			this.DepartmentUsedId = _departmentUsedId;
			this.PartnerId = _partnerId;
			this.WarDateTime = _warDateTime;
			this.DeadlineWar = _deadlineWar;
			this.Address = _address;
			this.PersonWar = _personWar;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="WarrantyAsset"/> instance.
		///</summary>
		///<param name="_id"></param>
		///<param name="_asssetId"></param>
		///<param name="_departmentUsedId"></param>
		///<param name="_partnerId"></param>
		///<param name="_warDateTime"></param>
		///<param name="_deadlineWar"></param>
		///<param name="_address"></param>
		///<param name="_personWar"></param>
		public static WarrantyAsset CreateWarrantyAsset(System.String _id, System.String _asssetId, System.String _departmentUsedId, 
			System.String _partnerId, System.DateTime _warDateTime, System.DateTime? _deadlineWar, 
			System.String _address, System.String _personWar)
		{
			WarrantyAsset newWarrantyAsset = new WarrantyAsset();
			newWarrantyAsset.Id = _id;
			newWarrantyAsset.AsssetId = _asssetId;
			newWarrantyAsset.DepartmentUsedId = _departmentUsedId;
			newWarrantyAsset.PartnerId = _partnerId;
			newWarrantyAsset.WarDateTime = _warDateTime;
			newWarrantyAsset.DeadlineWar = _deadlineWar;
			newWarrantyAsset.Address = _address;
			newWarrantyAsset.PersonWar = _personWar;
			return newWarrantyAsset;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 10)]
		public override System.String Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(WarrantyAssetColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(WarrantyAssetColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the Id property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the Id property.</remarks>
		/// <value>This type is varchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalId
		{
			get { return this.entityData.OriginalId; }
			set { this.entityData.OriginalId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the AsssetId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String AsssetId
		{
			get
			{
				return this.entityData.AsssetId; 
			}
			
			set
			{
				if (this.entityData.AsssetId == value)
					return;
				
                OnPropertyChanging("AsssetId");                    
				OnColumnChanging(WarrantyAssetColumn.AsssetId, this.entityData.AsssetId);
				this.entityData.AsssetId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(WarrantyAssetColumn.AsssetId, this.entityData.AsssetId);
				OnPropertyChanged("AsssetId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DepartmentUsedId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String DepartmentUsedId
		{
			get
			{
				return this.entityData.DepartmentUsedId; 
			}
			
			set
			{
				if (this.entityData.DepartmentUsedId == value)
					return;
				
                OnPropertyChanging("DepartmentUsedId");                    
				OnColumnChanging(WarrantyAssetColumn.DepartmentUsedId, this.entityData.DepartmentUsedId);
				this.entityData.DepartmentUsedId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(WarrantyAssetColumn.DepartmentUsedId, this.entityData.DepartmentUsedId);
				OnPropertyChanged("DepartmentUsedId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PartnerId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String PartnerId
		{
			get
			{
				return this.entityData.PartnerId; 
			}
			
			set
			{
				if (this.entityData.PartnerId == value)
					return;
				
                OnPropertyChanging("PartnerId");                    
				OnColumnChanging(WarrantyAssetColumn.PartnerId, this.entityData.PartnerId);
				this.entityData.PartnerId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(WarrantyAssetColumn.PartnerId, this.entityData.PartnerId);
				OnPropertyChanged("PartnerId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the WarDateTime property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime WarDateTime
		{
			get
			{
				return this.entityData.WarDateTime; 
			}
			
			set
			{
				if (this.entityData.WarDateTime == value)
					return;
				
                OnPropertyChanging("WarDateTime");                    
				OnColumnChanging(WarrantyAssetColumn.WarDateTime, this.entityData.WarDateTime);
				this.entityData.WarDateTime = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(WarrantyAssetColumn.WarDateTime, this.entityData.WarDateTime);
				OnPropertyChanged("WarDateTime");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DeadlineWar property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsDeadlineWarNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? DeadlineWar
		{
			get
			{
				return this.entityData.DeadlineWar; 
			}
			
			set
			{
				if (this.entityData.DeadlineWar == value)
					return;
				
                OnPropertyChanging("DeadlineWar");                    
				OnColumnChanging(WarrantyAssetColumn.DeadlineWar, this.entityData.DeadlineWar);
				this.entityData.DeadlineWar = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(WarrantyAssetColumn.DeadlineWar, this.entityData.DeadlineWar);
				OnPropertyChanged("DeadlineWar");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Address property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public virtual System.String Address
		{
			get
			{
				return this.entityData.Address; 
			}
			
			set
			{
				if (this.entityData.Address == value)
					return;
				
                OnPropertyChanging("Address");                    
				OnColumnChanging(WarrantyAssetColumn.Address, this.entityData.Address);
				this.entityData.Address = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(WarrantyAssetColumn.Address, this.entityData.Address);
				OnPropertyChanged("Address");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PersonWar property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String PersonWar
		{
			get
			{
				return this.entityData.PersonWar; 
			}
			
			set
			{
				if (this.entityData.PersonWar == value)
					return;
				
                OnPropertyChanging("PersonWar");                    
				OnColumnChanging(WarrantyAssetColumn.PersonWar, this.entityData.PersonWar);
				this.entityData.PersonWar = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(WarrantyAssetColumn.PersonWar, this.entityData.PersonWar);
				OnPropertyChanged("PersonWar");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Asset"/>.
		/// </summary>
		/// <value>The source Asset for AsssetId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Asset AsssetIdSource
      	{
            get { return entityData.AsssetIdSource; }
            set { entityData.AsssetIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="DepartmentUsed"/>.
		/// </summary>
		/// <value>The source DepartmentUsed for DepartmentUsedId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual DepartmentUsed DepartmentUsedIdSource
      	{
            get { return entityData.DepartmentUsedIdSource; }
            set { entityData.DepartmentUsedIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Partner"/>.
		/// </summary>
		/// <value>The source Partner for PartnerId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Partner PartnerIdSource
      	{
            get { return entityData.PartnerIdSource; }
            set { entityData.PartnerIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Id", "Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Id", "Id", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("AsssetId", "Assset Id", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("DepartmentUsedId", "Department Used Id", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("PartnerId", "Partner Id", 10));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Address", "Address"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Address", "Address", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("PersonWar", "Person War", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "WarrantyAsset"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "AsssetId", "DepartmentUsedId", "PartnerId", "WarDateTime", "DeadlineWar", "Address", "PersonWar"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as WarrantyAssetEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (WarrantyAsset) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<WarrantyAsset>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as WarrantyAsset);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed WarrantyAsset Entity 
		///</summary>
		protected virtual WarrantyAsset Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			WarrantyAsset copy = new WarrantyAsset();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
					copy.OriginalId = this.OriginalId;
				copy.AsssetId = this.AsssetId;
				copy.DepartmentUsedId = this.DepartmentUsedId;
				copy.PartnerId = this.PartnerId;
				copy.WarDateTime = this.WarDateTime;
				copy.DeadlineWar = this.DeadlineWar;
				copy.Address = this.Address;
				copy.PersonWar = this.PersonWar;
			
			if (this.AsssetIdSource != null && existingCopies.Contains(this.AsssetIdSource))
				copy.AsssetIdSource = existingCopies[this.AsssetIdSource] as Asset;
			else
				copy.AsssetIdSource = MakeCopyOf(this.AsssetIdSource, existingCopies) as Asset;
			if (this.DepartmentUsedIdSource != null && existingCopies.Contains(this.DepartmentUsedIdSource))
				copy.DepartmentUsedIdSource = existingCopies[this.DepartmentUsedIdSource] as DepartmentUsed;
			else
				copy.DepartmentUsedIdSource = MakeCopyOf(this.DepartmentUsedIdSource, existingCopies) as DepartmentUsed;
			if (this.PartnerIdSource != null && existingCopies.Contains(this.PartnerIdSource))
				copy.PartnerIdSource = existingCopies[this.PartnerIdSource] as Partner;
			else
				copy.PartnerIdSource = MakeCopyOf(this.PartnerIdSource, existingCopies) as Partner;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed WarrantyAsset Entity 
		///</summary>
		public virtual WarrantyAsset Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed WarrantyAsset Entity which is a deep copy of the current entity.
		///</summary>
		public virtual WarrantyAsset DeepCopy()
		{
			return EntityHelper.Clone<WarrantyAsset>(this as WarrantyAsset);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as WarrantyAssetEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new WarrantyAssetEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as WarrantyAssetEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(WarrantyAssetColumn column)
		{
			switch(column)
			{
					case WarrantyAssetColumn.Id:
					return entityData.Id != _originalData.Id;
					case WarrantyAssetColumn.AsssetId:
					return entityData.AsssetId != _originalData.AsssetId;
					case WarrantyAssetColumn.DepartmentUsedId:
					return entityData.DepartmentUsedId != _originalData.DepartmentUsedId;
					case WarrantyAssetColumn.PartnerId:
					return entityData.PartnerId != _originalData.PartnerId;
					case WarrantyAssetColumn.WarDateTime:
					return entityData.WarDateTime != _originalData.WarDateTime;
					case WarrantyAssetColumn.DeadlineWar:
					return entityData.DeadlineWar != _originalData.DeadlineWar;
					case WarrantyAssetColumn.Address:
					return entityData.Address != _originalData.Address;
					case WarrantyAssetColumn.PersonWar:
					return entityData.PersonWar != _originalData.PersonWar;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< WarrantyAssetColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.AsssetId != _originalData.AsssetId;
			result = result || entityData.DepartmentUsedId != _originalData.DepartmentUsedId;
			result = result || entityData.PartnerId != _originalData.PartnerId;
			result = result || entityData.WarDateTime != _originalData.WarDateTime;
			result = result || entityData.DeadlineWar != _originalData.DeadlineWar;
			result = result || entityData.Address != _originalData.Address;
			result = result || entityData.PersonWar != _originalData.PersonWar;
			return result;
		}	
		
		///<summary>
		///  Returns a WarrantyAsset Entity with the original data.
		///</summary>
		public WarrantyAsset GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateWarrantyAsset(
				_originalData.Id,
				_originalData.AsssetId,
				_originalData.DepartmentUsedId,
				_originalData.PartnerId,
				_originalData.WarDateTime,
				_originalData.DeadlineWar,
				_originalData.Address,
				_originalData.PersonWar
				);
				
			return (WarrantyAsset)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="WarrantyAssetBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is WarrantyAssetBase)
				return ValueEquals(this, (WarrantyAssetBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="WarrantyAssetBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					((this.AsssetId == null) ? string.Empty : this.AsssetId.ToString()).GetHashCode() ^ 
					((this.DepartmentUsedId == null) ? string.Empty : this.DepartmentUsedId.ToString()).GetHashCode() ^ 
					((this.PartnerId == null) ? string.Empty : this.PartnerId.ToString()).GetHashCode() ^ 
					this.WarDateTime.GetHashCode() ^ 
					((this.DeadlineWar == null) ? string.Empty : this.DeadlineWar.ToString()).GetHashCode() ^ 
					this.Address.GetHashCode() ^ 
					((this.PersonWar == null) ? string.Empty : this.PersonWar.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="WarrantyAssetBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(WarrantyAssetBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="WarrantyAssetBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="WarrantyAssetBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="WarrantyAssetBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(WarrantyAssetBase Object1, WarrantyAssetBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if ( Object1.AsssetId != null && Object2.AsssetId != null )
			{
				if (Object1.AsssetId != Object2.AsssetId)
					equal = false;
			}
			else if (Object1.AsssetId == null ^ Object2.AsssetId == null )
			{
				equal = false;
			}
			if ( Object1.DepartmentUsedId != null && Object2.DepartmentUsedId != null )
			{
				if (Object1.DepartmentUsedId != Object2.DepartmentUsedId)
					equal = false;
			}
			else if (Object1.DepartmentUsedId == null ^ Object2.DepartmentUsedId == null )
			{
				equal = false;
			}
			if ( Object1.PartnerId != null && Object2.PartnerId != null )
			{
				if (Object1.PartnerId != Object2.PartnerId)
					equal = false;
			}
			else if (Object1.PartnerId == null ^ Object2.PartnerId == null )
			{
				equal = false;
			}
			if (Object1.WarDateTime != Object2.WarDateTime)
				equal = false;
			if ( Object1.DeadlineWar != null && Object2.DeadlineWar != null )
			{
				if (Object1.DeadlineWar != Object2.DeadlineWar)
					equal = false;
			}
			else if (Object1.DeadlineWar == null ^ Object2.DeadlineWar == null )
			{
				equal = false;
			}
			if (Object1.Address != Object2.Address)
				equal = false;
			if ( Object1.PersonWar != null && Object2.PersonWar != null )
			{
				if (Object1.PersonWar != Object2.PersonWar)
					equal = false;
			}
			else if (Object1.PersonWar == null ^ Object2.PersonWar == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((WarrantyAssetBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static WarrantyAssetComparer GetComparer()
        {
            return new WarrantyAssetComparer();
        }
        */

        // Comparer delegates back to WarrantyAsset
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(WarrantyAsset rhs, WarrantyAssetColumn which)
        {
            switch (which)
            {
            	
            	
            	case WarrantyAssetColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case WarrantyAssetColumn.AsssetId:
            		return this.AsssetId.CompareTo(rhs.AsssetId);
            		
            		                 
            	
            	
            	case WarrantyAssetColumn.DepartmentUsedId:
            		return this.DepartmentUsedId.CompareTo(rhs.DepartmentUsedId);
            		
            		                 
            	
            	
            	case WarrantyAssetColumn.PartnerId:
            		return this.PartnerId.CompareTo(rhs.PartnerId);
            		
            		                 
            	
            	
            	case WarrantyAssetColumn.WarDateTime:
            		return this.WarDateTime.CompareTo(rhs.WarDateTime);
            		
            		                 
            	
            	
            	case WarrantyAssetColumn.DeadlineWar:
            		return this.DeadlineWar.Value.CompareTo(rhs.DeadlineWar.Value);
            		
            		                 
            	
            	
            	case WarrantyAssetColumn.Address:
            		return this.Address.CompareTo(rhs.Address);
            		
            		                 
            	
            	
            	case WarrantyAssetColumn.PersonWar:
            		return this.PersonWar.CompareTo(rhs.PersonWar);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<WarrantyAssetKey> Members
		
		// member variable for the EntityId property
		private WarrantyAssetKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual WarrantyAssetKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new WarrantyAssetKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("WarrantyAsset")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{9}{8}- Id: {0}{8}- AsssetId: {1}{8}- DepartmentUsedId: {2}{8}- PartnerId: {3}{8}- WarDateTime: {4}{8}- DeadlineWar: {5}{8}- Address: {6}{8}- PersonWar: {7}{8}{10}", 
				this.Id,
				(this.AsssetId == null) ? string.Empty : this.AsssetId.ToString(),
				(this.DepartmentUsedId == null) ? string.Empty : this.DepartmentUsedId.ToString(),
				(this.PartnerId == null) ? string.Empty : this.PartnerId.ToString(),
				this.WarDateTime,
				(this.DeadlineWar == null) ? string.Empty : this.DeadlineWar.ToString(),
				this.Address,
				(this.PersonWar == null) ? string.Empty : this.PersonWar.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'WarrantyAsset' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class WarrantyAssetEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "WarrantyAsset"</remarks>
		public System.String Id;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.String OriginalId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// AsssetId : 
		/// </summary>
		public System.String AsssetId = null;
		
		/// <summary>
		/// DepartmentUsedId : 
		/// </summary>
		public System.String DepartmentUsedId = null;
		
		/// <summary>
		/// PartnerId : 
		/// </summary>
		public System.String PartnerId = null;
		
		/// <summary>
		/// WarDateTime : 
		/// </summary>
		public System.DateTime WarDateTime = DateTime.MinValue;
		
		/// <summary>
		/// DeadlineWar : 
		/// </summary>
		public System.DateTime? DeadlineWar = null;
		
		/// <summary>
		/// Address : 
		/// </summary>
		public System.String Address = string.Empty;
		
		/// <summary>
		/// PersonWar : 
		/// </summary>
		public System.String PersonWar = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Asset _asssetIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Asset"/>.
		/// </summary>
		/// <value>The source Asset for AsssetId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Asset AsssetIdSource
      	{
            get { return this._asssetIdSource; }
            set { this._asssetIdSource = value; }
      	}
		private DepartmentUsed _departmentUsedIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="DepartmentUsed"/>.
		/// </summary>
		/// <value>The source DepartmentUsed for DepartmentUsedId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual DepartmentUsed DepartmentUsedIdSource
      	{
            get { return this._departmentUsedIdSource; }
            set { this._departmentUsedIdSource = value; }
      	}
		private Partner _partnerIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Partner"/>.
		/// </summary>
		/// <value>The source Partner for PartnerId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Partner PartnerIdSource
      	{
            get { return this._partnerIdSource; }
            set { this._partnerIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			WarrantyAssetEntityData _tmp = new WarrantyAssetEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.AsssetId = this.AsssetId;
			_tmp.DepartmentUsedId = this.DepartmentUsedId;
			_tmp.PartnerId = this.PartnerId;
			_tmp.WarDateTime = this.WarDateTime;
			_tmp.DeadlineWar = this.DeadlineWar;
			_tmp.Address = this.Address;
			_tmp.PersonWar = this.PersonWar;
			
			#region Source Parent Composite Entities
			if (this.AsssetIdSource != null)
				_tmp.AsssetIdSource = MakeCopyOf(this.AsssetIdSource) as Asset;
			if (this.DepartmentUsedIdSource != null)
				_tmp.DepartmentUsedIdSource = MakeCopyOf(this.DepartmentUsedIdSource) as DepartmentUsed;
			if (this.PartnerIdSource != null)
				_tmp.PartnerIdSource = MakeCopyOf(this.PartnerIdSource) as Partner;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			WarrantyAssetEntityData _tmp = new WarrantyAssetEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.AsssetId = this.AsssetId;
			_tmp.DepartmentUsedId = this.DepartmentUsedId;
			_tmp.PartnerId = this.PartnerId;
			_tmp.WarDateTime = this.WarDateTime;
			_tmp.DeadlineWar = this.DeadlineWar;
			_tmp.Address = this.Address;
			_tmp.PersonWar = this.PersonWar;
			
			#region Source Parent Composite Entities
			if (this.AsssetIdSource != null && existingCopies.Contains(this.AsssetIdSource))
				_tmp.AsssetIdSource = existingCopies[this.AsssetIdSource] as Asset;
			else
				_tmp.AsssetIdSource = MakeCopyOf(this.AsssetIdSource, existingCopies) as Asset;
			if (this.DepartmentUsedIdSource != null && existingCopies.Contains(this.DepartmentUsedIdSource))
				_tmp.DepartmentUsedIdSource = existingCopies[this.DepartmentUsedIdSource] as DepartmentUsed;
			else
				_tmp.DepartmentUsedIdSource = MakeCopyOf(this.DepartmentUsedIdSource, existingCopies) as DepartmentUsed;
			if (this.PartnerIdSource != null && existingCopies.Contains(this.PartnerIdSource))
				_tmp.PartnerIdSource = existingCopies[this.PartnerIdSource] as Partner;
			else
				_tmp.PartnerIdSource = MakeCopyOf(this.PartnerIdSource, existingCopies) as Partner;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="WarrantyAssetColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(WarrantyAssetColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="WarrantyAssetColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(WarrantyAssetColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="WarrantyAssetColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(WarrantyAssetColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				WarrantyAssetEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new WarrantyAssetEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="WarrantyAssetColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(WarrantyAssetColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				WarrantyAssetEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new WarrantyAssetEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region WarrantyAssetEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="WarrantyAsset"/> object.
	/// </remarks>
	public class WarrantyAssetEventArgs : System.EventArgs
	{
		private WarrantyAssetColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the WarrantyAssetEventArgs class.
		///</summary>
		public WarrantyAssetEventArgs(WarrantyAssetColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the WarrantyAssetEventArgs class.
		///</summary>
		public WarrantyAssetEventArgs(WarrantyAssetColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The WarrantyAssetColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="WarrantyAssetColumn" />
		public WarrantyAssetColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all WarrantyAsset related events.
	///</summary>
	public delegate void WarrantyAssetEventHandler(object sender, WarrantyAssetEventArgs e);
	
	#region WarrantyAssetComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class WarrantyAssetComparer : System.Collections.Generic.IComparer<WarrantyAsset>
	{
		WarrantyAssetColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:WarrantyAssetComparer"/> class.
        /// </summary>
		public WarrantyAssetComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:WarrantyAssetComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public WarrantyAssetComparer(WarrantyAssetColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="WarrantyAsset"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="WarrantyAsset"/> to compare.</param>
        /// <param name="b">The second <c>WarrantyAsset</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(WarrantyAsset a, WarrantyAsset b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(WarrantyAsset entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(WarrantyAsset a, WarrantyAsset b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public WarrantyAssetColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region WarrantyAssetKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="WarrantyAsset"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class WarrantyAssetKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the WarrantyAssetKey class.
		/// </summary>
		public WarrantyAssetKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the WarrantyAssetKey class.
		/// </summary>
		public WarrantyAssetKey(WarrantyAssetBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the WarrantyAssetKey class.
		/// </summary>
		public WarrantyAssetKey(System.String _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private WarrantyAssetBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public WarrantyAssetBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.String _id;
		
		/// <summary>
		/// Gets or sets the Id property.
		/// </summary>
		public System.String Id
		{
			get { return _id; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.String) EntityUtil.ChangeType(values["Id"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",
								Id,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region WarrantyAssetColumn Enum
	
	/// <summary>
	/// Enumerate the WarrantyAsset columns.
	/// </summary>
	[Serializable]
	public enum WarrantyAssetColumn : int
	{
		/// <summary>
		/// Id : 
		/// </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.String), System.Data.DbType.AnsiString, true, false, false, 10)]
		Id = 1,
		/// <summary>
		/// AsssetId : 
		/// </summary>
		[EnumTextValue("AsssetId")]
		[ColumnEnum("AsssetId", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 10)]
		AsssetId = 2,
		/// <summary>
		/// DepartmentUsedId : 
		/// </summary>
		[EnumTextValue("DepartmentUsedId")]
		[ColumnEnum("DepartmentUsedId", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 10)]
		DepartmentUsedId = 3,
		/// <summary>
		/// PartnerId : 
		/// </summary>
		[EnumTextValue("PartnerId")]
		[ColumnEnum("PartnerId", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 10)]
		PartnerId = 4,
		/// <summary>
		/// WarDateTime : 
		/// </summary>
		[EnumTextValue("WarDateTime")]
		[ColumnEnum("WarDateTime", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		WarDateTime = 5,
		/// <summary>
		/// DeadlineWar : 
		/// </summary>
		[EnumTextValue("DeadlineWar")]
		[ColumnEnum("DeadlineWar", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		DeadlineWar = 6,
		/// <summary>
		/// Address : 
		/// </summary>
		[EnumTextValue("Address")]
		[ColumnEnum("Address", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		Address = 7,
		/// <summary>
		/// PersonWar : 
		/// </summary>
		[EnumTextValue("PersonWar")]
		[ColumnEnum("PersonWar", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		PersonWar = 8
	}//End enum

	#endregion WarrantyAssetColumn Enum

} // end namespace
